import * as fs from 'fs';
import * as path from 'path';
import * as loadJsonFile from 'load-json-file';

import { UserConfig } from '../../global';
import { getTeamId } from '../misc/teamUtils';

// Get data from streams cache
// This assumes caches have been generated previously generated by the streams command
export const getStreamsCachePerTeam = (
  userConfig: UserConfig,
  cacheDir: string,
) => {
  const teamsCache = [];
  for (const team of userConfig.teams) {
    const teamCacheFile = path.join(
      cacheDir,
      `stream-artifacts-${getTeamId(team.name)}.json`,
    );
    if (fs.existsSync(teamCacheFile)) {
      const teamData: any = loadJsonFile.sync(teamCacheFile);
      teamsCache.push(teamData);
    }
  }
  return teamsCache;
};
